# These are supported funding model platforms

ko_fi: andrescera
custom: ["https://www.paypal.com/donate/?business=7KKQS9KBSAMNE&no_recurring=0&item_name=CERALIVE+Development+Support&currency_code=USD"]
